### ISSUE TITLE
Overwrite event ticket template does not work.

### ISSUE THREAD

**Issue by rtwlabs** [helgatheviking/woocommerce-name-your-price-event-tickets#10]
Events Calendar 6.0.3.1
Events Calendar Pro 6.0.2.1
Event Tickets 5.5.4
Event Tickets Plus 5.6.3
WooCommerce 7.1.0
WooCommerce Name Your Price 3.3.2
WooCommerce Name Your Price - Events Tickets 2.0.0-rc.1

I am trying to move the Suggested price box from above the donation input box to below it by overwriting the nyp-price.php file by placing it at 

[your-theme]/tribe/tickets/v2/tickets/item/extra/nyp-price.php

And deleting the code required.

<?php echo WC_Name_Your_Price()->display->display_suggested_price( $ticket->ID ); ?>

However, in doing so and removing the line that controls this text, it does not remove it. If I edit the plugin file directly and its template in WooCommerce Name Your Price - Events Tickets it will remove it.

It appears placing the nyp-price.php template file in my child theme does not override as intended.

**Comment by helgatheviking** [comment]
Hi, I don't work with Events often enough to really know what's going on there. Best guess is something is missing from the [custom `Tribe__Tickets__NYP__Template` class](https://github.com/kathyisawesome/wc-nyp-event-tickets/blob/trunk/includes/class-tribe-tickets-nyp-template.php). If you are able to resolve it, I am certainly open to pull requests.

**Comment by rtwlabs** [comment]
No problem will take a look, and if we find the cause will flag a request

**Comment by helgatheviking** [comment]
Looks like you can copy the file to `[your-theme]/tribe/templates/v2/tickets/item/extra/nyp-price.php`

I don't understand _why_ it's like that or how to customize the path, but that seems to work for me. I have a question out to the Events team and maybe they can advise further. 

Event tickets appears to [filter the template path](https://github.com/the-events-calendar/event-tickets/blob/1516c754695899eed12db2605067359c5cb0fda2/src/Tribe/Events/Views/V2/Hooks.php#L52) but I don't see how they are getting from `src/views` to `theme/tribe/event-tickets/`.

**Comment by rtwlabs** [comment]
I'll try moving the file over to that new location and see how it goes on. 

I've had issues in the past with the correct path to drop templates files to overwrite their templates so not surprised it's not in the place you'd expect it to be

**Comment by helgatheviking** [comment]
Custom paths seem to require way more of a setup than I noticed originally and more than I could figure out today unfortunately.

**Comment by helgatheviking** [comment]
Fairly sure this is working now in 2.0.1 Please check:
https://github.com/kathyisawesome/wc-nyp-event-tickets/releases/download/2.0.1/wc-nyp-event-tickets-2.0.1.zip

The template location should be `[your-theme]/tribe/wc-nyp-event-tickets/v2/tickets/item/extra/nyp-price.php`

**Comment by rtwlabs** [comment]
Thanks @helgatheviking can confirm this now works as expected.
