### ISSUE TITLE
fatal error upon Activation

### ISSUE THREAD

**Issue by wonderandwilder** [helgatheviking/woocommerce-name-your-price-event-tickets#11]
<img width="974" alt="Screen Shot 2022-12-28 at 10 58 23 AM" src="https://user-images.githubusercontent.com/121565582/209833866-3dab87be-72a0-47e4-a333-ab1e3350489d.png">

I tried deactivating all plugins except Event Calendar, Tickets Plus, WooCommerce, and NYP plugins active and it still crashed. 

Error Details
=============
An error of type E_ERROR was caused in line 8 of the file /var/www/vhosts/[wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/includes/class-tribe-tickets-nyp-template.php](http://wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/includes/class-tribe-tickets-nyp-template.php). Error message: Uncaught Error: Class 'Tribe__Tickets_Plus__Template' not found in /var/www/vhosts/[wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/includes/class-tribe-tickets-nyp-template.php:8](http://wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/includes/class-tribe-tickets-nyp-template.php:8)
Stack trace:
#0 /var/www/vhosts/[wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/includes/class-wc-nyp-event-tickets-display.php(27)](http://wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/includes/class-wc-nyp-event-tickets-display.php(27)): include_once()
#1 /var/www/vhosts/[wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/includes/class-wc-nyp-event-tickets-display.php(337)](http://wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/includes/class-wc-nyp-event-tickets-display.php(337)): WC_NYP_Tickets_Display->__construct()
#2 /var/www/vhosts/[wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/wc-nyp-event-tickets.php(200)](http://wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/wc-nyp-event-tickets.php(200)): include_once('/var/www/vhosts...')
#3 /var/www/vhosts/[wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/wc-nyp-event-tickets.php(119)](http://wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/wc-nyp-event-tickets.php(119)): WC_NYP_Tickets->required_files()
#4 /var/www/vhosts/[wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/wc-nyp-event-tickets.php(96)](http://wonderandwilder.com/httpdocs/wp-content/plugins/wc-nyp-event-tickets/wc-nyp-event-tickets.php(96)): WC_NYP_Tickets->__construct()
#5 /var/www/vhosts/wo

**Comment by helgatheviking** [comment]
Hi, thanks for reporting this. Can you let me know what versions of everything you are using?

As a reminder this plugin does not receive priority  support/maintenance, as is worked on when i have time. I'm on holiday until atleast next week.

Very open to pull requests though if you can find a solution sooner.

**Comment by helgatheviking** [comment]
I can't reproduce this. When the other plugins aren't active, I get an admin notice saying the plugin is inactive:

>Name Your Price Tickets is inactive. The [Events Ticket Plus plugin](https://theeventscalendar.com/product/wordpress-event-tickets-plus/) must be active and at least version 5.2.10 for Name Your Price Tickets to function.

Please make sure you are using the [latest version 2.0.1](https://github.com/kathyisawesome/wc-nyp-event-tickets/releases/tag/2.0.1)
